# Generated by Django 4.2.5 on 2023-11-01 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("prodname", models.CharField(blank=True, max_length=150, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("imgid", models.ImageField(blank=True, null=True, upload_to="")),
                ("price", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "statusid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "status",
                "managed": True,
            },
        ),
    ]
