# Generated by Django 4.2.5 on 2023-11-01 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lelang", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="imgid",
            new_name="img",
        ),
    ]
